---
- hosts: all
  become: yes
  tasks:
    - name: install apache2 and php
      package:
        name: 
          - "{{ apache_package  }}"
          - "{{ php_package  }}"
        state: latest
        update_cache: yes

