---
- hosts: all
  become: yes
  pre_tasks:
    - name: update_cache (Ubuntu)
      tags: always
      apt:
        update_cache: yes
      changed_when: false
      when: ansible_distribution == "Ubuntu"

    - name: update_cache (centos)
      tags: always
      yum:
        update_cache: yes
      changed_when: false
      when: ansible_distribution == "CentOS"

- hosts: all
  become: yes
  roles:
    - base

- hosts: workstations
  become: yes
  roles:
    - workstations

- hosts: web_servers
  become: yes
  roles:
    - web_servers

- hosts: db_servers
  become: yes
  roles:
    - db_servers