- name: add ssh key for simone
  authorized_key:
    user: simone
    key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCkBZ0FKQNRJrHNLNfwDSqFK19ifPqWQL1orrTawaYNJceep5iEKEd9ELoHFw8Ns5U3TbXJTaDna68XHhKt1F98femmkce7NlPXjrIOVk0kJDzOXvpmnSEZH2k2qwl1F4GyoRM4k4jBDZY3Nfg7bXF1hLr6hR6MO+0HCepI57gFLPz1KgkVkG0l4jbpJjQUkeAn+mnKo64KCFKNGB/LKE0YP856ltuVkLkS/UfPChozm88MQephqNUBqm0R0UnTI4Bs6PHyJSjciH1fqX+HFe/1sToUi54mZnVukDAwrWf3jqUnbI2+T+RL57GzH6Ncrlr+52kVI6Quj17qL7puWWLUG9um1yq2GndN2u8E3ILjn75kc6PhXsnh4B3nvb24j86elylN2EgJB1YQUSMUQU+kBYRu8mG84Pb1aL3tj+N1jXsi9EupTFBkw0CZxafTjEsfTELDVCoM4lJXUNKiAJ+2wIYQwkUGFbQtLzMdBcgoLEPyZMkXgtwckkwvvTdEBX8= ansible@ansiblecontroller"

- name: copy sshd_config file from ssh_template_file
  tags: ssh
  template:
    src: "{{ ssh_template_file }}"
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: 644
  notify: restart_ssh
