- name: install unzip
  package:
    name: unzip
    state: latest

- name: install teraform on workstations
  unarchive:
    src: https://releases.hashicorp.com/terraform/1.1.3/terraform_1.1.3_linux_amd64.zip
    dest: /usr/local/bin
    remote_src: yes
    mode: 0755
    owner: root
    group: root
